3-manifolds/Spherogram

spherogram_src/graphs.py, spherogram_src/links/alexander.py, spherogram_src/links/invariants.py, spherogram_src/links/jones.py, spherogram_src/links/morse.py, spherogram_src/links/random_links.py, spherogram_src/links/simplify.py
typos in various files, more pep8 changes in one file and some whitespace removal
=> a bunch of typos and whitespace changes

planarmap_src/planarmap.pyx, spherogram_src/presentations.py
some details
* first autopep8
* then some python3 changes : no xrange, no cmp
* other code details and typos
=> better python3 compatibility for presentations.py

spherogram_src/links/seifert.py
* ran autopep8 to fix some formatting
* removed trailing whitespace
* simplified some code
* manual fine tuning (spaces around + and -) so that flake8 is happy
=> refresh seifert.py (full flake8)

spherogram_src/links/morse.py
autope8 for code formatting
a few other manual changes
also removing one unused import and adding a missing one
so the result is full compliant with flake8
=> autopep8 and refresh the file morse.py

spherogram_src/links/exhaust.py, spherogram_src/links/ordered_set.py, spherogram_src/links/orthogonal.py
namely
exhaust.py
orthogonal.py
spherogram_src/links/ordered_set.py
=> autopep8 cleanup and refresh of 3 files in links

spherogram_src/links/draw.py, spherogram_src/links/links_base.py
namely autopep8 cleanup, then manual care for remaining flake8 details
There were 2  "copy" methods, so  I removed one
=> Details in draw and links base

dev/DTcodes.py, spherogram_src/codecs/DT.py, spherogram_src/links/tangles.py
mainly making a full pep8 cleanup of tangles.py
also removing some python3-conditional code in two other files
=> full cleanup of tangle.py, plus some other py3 stuff

dev/DTcodes.py, dev/dev_malik/mutation/mutants.py, dev/dev_malik/mutation/tangle_patch.py, dev/dev_malik/petal_diagram/random_petaluma.py, dev/dev_malik/thompson/homomorphisms.py, dev/dev_malik/thompson/thompson.py, dev/tangle_patch.py, spherogram_src/codecs/DT.py, spherogram_src/links/invariants.py, spherogram_src/links/jones_old.py, spherogram_src/links/simplify.py, spherogram_src/sage_helper.py, spherogram_src/test_helper.py
and a few other cosmetic changes in the code
=> get rid of pycodestyle E701 (multiple statements on one line (colon))

dev/DTcodes.py, dev/dev_jennet/AlexanderKauffman.py, dev/dev_malik/knots/random_knots.py, dev/dev_malik/mutation/tangle_patch.py, dev/dev_malik/random_knot.py, dev/dev_malik/thompson/graphknotter.py, dev/orthogonal/orthogonal.py, dev/tangle_patch.py, setup.py, spherogram_src/graphs.py, spherogram_src/links/jones.py, spherogram_src/links/planar_isotopy.py
about comparison to None, True, False
plus a few other details "en passant"
=> fix pycodestyle warnings E71

spherogram_src/links/torus.py, spherogram_src/links/twist.py
in torus:
refactor and simplify the code, make pylint happy.
in twist, a few pep8 details only.
=> cleaning torus.py and twist.py

spherogram_src/__init__.py, spherogram_src/graphs.py, spherogram_src/links/invariants.py, spherogram_src/links/jones_old.py, spherogram_src/links/links.py, spherogram_src/links/planar_isotopy.py, spherogram_src/links/random_links.py, spherogram_src/links/simplify.py, spherogram_src/links/test/__init__.py, spherogram_src/sage_helper.py, spherogram_src/test_helper.py
trailing whitespaces removed, and spaces before comments added
=> pycodestyle cleanup for whitespaces in spherogram_src

spherogram_src/__init__.py, spherogram_src/graphs.py, spherogram_src/links/invariants.py, spherogram_src/links/jones_old.py, spherogram_src/links/random_links.py, spherogram_src/links/simplify.py, spherogram_src/links/test/__init__.py
=> more pycodestyle formatting in spherogram_src

dev/dev_malik/knots/random_knots.py, dev/dev_malik/random_knot.py, spherogram_src/graphs.py, spherogram_src/links/invariants.py, spherogram_src/links/simplify.py
also turning one method into an iterator. This method is only used once, inside a loop.
=> fix spaces around brackets and parenthesis in spherogram_src

spherogram_src/links/invariants.py
* fixes all pycodestyle warning
* fixes some pylint warnings (more serious, maybe)
=> cleaning the file spherogram_src/links/invariants.py

spherogram_src/codecs/DT.py, spherogram_src/graphs.py, spherogram_src/links/alexander.py, spherogram_src/links/exhaust.py, spherogram_src/links/jones.py, spherogram_src/links/links_base.py, spherogram_src/links/morse.py, spherogram_src/links/seifert.py, spherogram_src/links/simplify.py, spherogram_src/links/tangles.py, spherogram_src/presentations.py
in python3, classes no longer need to subclass object
other fixes:
- use set comprehension and dict comprehension
- a few better boolean tests
=> in spherogram_src, no longer use object, use set comprehensions

dev/DTcodes.py, dev/dt_tests.py, dev/old/fastalex/exhaust.py, dev/orthogonal/bridge.py, dev/sage_graph.py
as this is no longer needed in python3
=> remove inheritance of object

spherogram_src/graphs.py, spherogram_src/links/exhaust.py, spherogram_src/links/ordered_set.py, spherogram_src/links/simplify.py, spherogram_src/presentations.py
some change about pep8 compliance
also a few tweaks to the code
=> various details and code cleaning

dev/orthogonal/hobby.py
as "apply" no longer exists in python3
=> repair and clean hobby.py

dev/dev_malik/mutation/link_planar_isotopy.py, dev/dev_malik/mutation/tangle_patch.py, dev/dev_malik/random_knot.py, dev/dev_malik/thompson/graphknotter.py, dev/dev_malik/thompson/thompson.py, dev/dev_malik/unknotting_number.py, dev/old/seifert_patch.py, dev/orthogonal/orthogonal.py, dev/tangle_patch.py
and also some details in the code around, in some places
=> fix E251 in dev/

dev/DTcodes.py, dev/dev_malik/mutation/tangle_patch.py, dev/dt_issue.py, dev/old/fastalex/exhaust.py, dev/orthogonal/bridge.py, dev/orthogonal/orthogonal.py, dev/orthogonal/smooth.py, dev/sage_link_compare.py, dev/signature.py, setup.py, spherogram_src/codecs/DT.py, spherogram_src/links/links_base.py, spherogram_src/links/morse.py, spherogram_src/links/simplify.py, spherogram_src/links/torus.py
found using
`sage --tox -e rst .`
and
`sage --tox -e pycodestyle-minimal .`
=> fix all rst issues and a few pep8 details

dev/dev_malik/thompson/thompson.py, spherogram_src/graphs.py, spherogram_src/links/links_base.py, spherogram_src/presentations.py
=> use iterator in join

dev/orthogonal/bridge.py, dev/orthogonal/orthogonal.py, dev/orthogonal/smooth.py
mostly code formatting but also
- removing a duplicate function
- using point2d instead of point
- removing unused imports
=> pep8 in dev/orthogonal

spherogram_src/codecs/DT.py, spherogram_src/links/jones.py, spherogram_src/links/links_base.py, spherogram_src/links/ordered_set.py, spherogram_src/links/random_links.py
- testing without using len
- using any
- changing one function to an iterator
- using max with default value
=> various small changes, some about len

dev/dev_malik/knots/random_knots.py, dev/dev_malik/mutation/link_planar_isotopy.py, dev/dev_malik/mutation/tangle_patch.py, dev/dev_malik/petal_diagram/random_petaluma.py, dev/dev_malik/tangle_nhds/tangle_nhd.py, dev/dev_malik/thompson/graphknotter.py, dev/dev_malik/thompson/homomorphisms.py, dev/dev_malik/thompson/thompson.py, setup.py
about
```
42      W291 trailing whitespace
43      W293 blank line contains whitespace
2       W391 blank line at end of file
```
done entirely using autopep8
=> fix a lot of W2 and W3 using autope8

.github/workflows/lint.yml, spherogram_src/links/jones_old.py, spherogram_src/links/links_base.py, spherogram_src/links/simplify.py
This is just a first sketch. The configuration will certainly needs to be tweaked until the lights come back green.
=> add linter (codespell and pycodestyle)

spherogram_src/codecs/Base64LikeDT.py, spherogram_src/codecs/DT.py, spherogram_src/graphs.py, spherogram_src/links/extra_tests.py, spherogram_src/links/invariants.py, spherogram_src/links/links_base.py, spherogram_src/links/test/old_testing_code.py, spherogram_src/presentations.py
mainly about using iterators more
=> some little changes in the code, as suggested by pylint

spherogram_src/graphs.py, spherogram_src/links/morse.py, spherogram_src/sage_helper.py, spherogram_src/test.py
- turning one function into an iterator
- avoid `issubset` in another function
- remove some unused imports
=> some minor code details

spherogram_src/links/invariants.py, spherogram_src/links/jones_old.py, spherogram_src/links/orthogonal.py, spherogram_src/links/simplify.py, spherogram_src/links/tangles.py, spherogram_src/links/test/__init__.py, spherogram_src/links/torus.py
A few changes, notably using more precise exceptions
=> some minor changes in the code, including some about exceptions

.github/workflows/lint.yml, planarity_src/planarity.pyx, planarmap_src/planarmap.pyx
this proposes to use `cython-lint` for some checks in cython code
=> fix and activate the cython-lint checker workflow

.github/workflows/lint.yml, dev/DTcodes.py, dev/dev_jennet/spanning_trees.py, dev/dev_jennet/test_links.py, dev/dev_malik/fast_jones_patch.py, dev/dev_malik/knots/random_knots.py, dev/dev_malik/mutation/link_planar_isotopy.py, dev/dev_malik/mutation/tangle_patch.py, dev/dev_malik/petal_diagram/random_petaluma.py, dev/dev_malik/random_knot.py, dev/dev_malik/thompson/graphknotter.py, dev/dev_malik/thompson/thompson.py, dev/old/braidclosure.py, dev/old/seifert_patch.py, dev/orthogonal/orthogonal.py, dev/signature.py, dev/tangle_patch.py
this is fixing and checking one more pycodestyle check
=> fix and activate pycodestyle E225 in dev/
